#!/usr/bin/env bash
#
# Step 1 of repo slimming: work out what would be removed, and prove it is worth
# doing, without changing anything.
#
# Writes two files next to this script:
#   removal-paths.txt   the exact path list slim.sh will strip (review this)
#   analysis.txt        a human-readable report
#
# Nothing here mutates the repository. Run it, read removal-paths.txt, and only
# then run slim.sh.
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REMOVAL="$HERE/removal-paths.txt"
REPORT="$HERE/analysis.txt"

# Small fixtures that must survive. Everything else under the stripped prefixes
# goes. Keep this list short and justify each entry.
#
#   isoncorrect/{0,1}.fastq  -> used by CI and by bench/equivalence.sh
#   100reads.fq, six_exons.fa, sirv_transcriptome*.fasta
#                            -> referenced by scripts/ (paper reproduction), all <100 KB
#
# test_data/chr6_ensemble.fa is deliberately NOT kept: 18 MB and unused by any test.
KEEP=(
  "test_data/isoncorrect/0.fastq"
  "test_data/isoncorrect/1.fastq"
  "test_data/100reads.fq"
  "test_data/six_exons.fa"
  "test_data/sirv_transcriptome.fasta"
  "test_data/sirv_transcriptome_flat.fasta"
  "test_data/sirv_transcriptome_flat_non_redundant.fasta"
)

# Prefixes whose contents are stripped from all history unless listed in KEEP.
STRIP_PREFIXES=("data/" "test_data/")

cd "$REPO_ROOT"

echo "==> enumerating every object in history (this takes a minute on a 2.4 GB repo)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

git rev-list --objects --all > "$TMP/allobj.txt"
awk 'NF>1' "$TMP/allobj.txt" > "$TMP/withpath.txt"
cut -d' ' -f1 "$TMP/withpath.txt" \
  | git cat-file --batch-check='%(objectname) %(objecttype) %(objectsize)' > "$TMP/sizes.txt"

# The removal list MUST come from a tree walk, not from the object listing.
# `git rev-list --objects` emits each blob exactly once with a single path, so
# any file whose content is byte-identical to another file is invisible there --
# test_data/chr6_ensemble.fa is deduplicated against data/chr6_transcripts.fa and
# would silently survive the rewrite. This enumerates every path ever committed.
echo "==> enumerating every path ever committed"
git log --all --pretty=format: --name-only --no-renames \
  | sed '/^$/d' | LC_ALL=C sort -u > "$TMP/allpaths.txt"
echo "    $(wc -l < "$TMP/allpaths.txt" | tr -d ' ') distinct paths in history"

echo "==> classifying"
KEEP_JOINED="$(printf '%s\n' "${KEEP[@]}")"
PREFIX_JOINED="$(printf '%s\n' "${STRIP_PREFIXES[@]}")"

KEEP_LIST="$KEEP_JOINED" PREFIX_LIST="$PREFIX_JOINED" \
python3 - "$TMP/withpath.txt" "$TMP/sizes.txt" "$REMOVAL" "$REPORT" "$TMP/allpaths.txt" <<'PY'
import os, sys
from collections import defaultdict

withpath, sizesf, removal_out, report_out, allpathsf = sys.argv[1:6]
keep = {l for l in os.environ["KEEP_LIST"].splitlines() if l}
prefixes = tuple(l for l in os.environ["PREFIX_LIST"].splitlines() if l)

sizes = {}
for line in open(sizesf):
    p = line.split()
    if len(p) == 3 and p[1] == "blob":
        sizes[p[0]] = int(p[2])

# A blob can be reachable at several paths and git stores it once, so attribute
# each distinct blob to the first path that reaches it and never double count.
# The authoritative removal list: every path ever committed under a stripped
# prefix that is not explicitly kept. Derived from the tree walk, so
# content-deduplicated paths are included.
strip_paths = {
    p for p in (l.rstrip("\n") for l in open(allpathsf))
    if p and p.startswith(prefixes) and p not in keep
}

seen = set()
strip_bytes = defaultdict(int)
keep_bytes = defaultdict(int)
other_total = 0
total = 0

# `git rev-list --objects` emits each object exactly once, with whichever path
# reached it first, so this loop cannot be used to decide whether a given path
# exists -- deduplicated paths simply never appear. Fixture existence is checked
# separately, against the trees, after this step.
for line in open(withpath):
    sha, _, path = line.partition(" ")
    path = path.strip()
    if sha not in sizes or sha in seen:
        continue
    seen.add(sha)
    size = sizes[sha]
    total += size
    if path in strip_paths:
        strip_bytes[path] += size
    elif path in keep:
        keep_bytes[path] += size
    else:
        other_total += size

with open(removal_out, "w") as fh:
    fh.write("# Paths stripped from ALL history by tools/repo-slim/slim.sh.\n")
    fh.write("# Generated by analyze.sh -- review before running slim.sh.\n")
    fh.write("# Format is git-filter-repo --paths-from-file: one literal path per line.\n")
    for p in sorted(strip_paths):
        fh.write(p + "\n")

stripped_total = sum(strip_bytes.values())
kept_total = sum(keep_bytes.values())

lines = []
w = lines.append
w("Repository slimming analysis")
w("=" * 60)
w("")
w(f"total distinct blob bytes in history : {total/1e9:8.3f} GB")
w(f"  to be stripped                     : {stripped_total/1e9:8.3f} GB  ({100*stripped_total/total:.1f}%)")
w(f"  retained (source, scripts, docs)   : {other_total/1e9:8.3f} GB")
w(f"  retained fixtures under test_data/ : {kept_total/1e6:8.3f} MB")
w("")
w(f"paths stripped: {len(strip_paths)}")
w("")
w("Largest paths being removed")
w("-" * 60)
for p, s in sorted(strip_bytes.items(), key=lambda x: -x[1])[:25]:
    w(f"  {s/1e6:10.2f} MB  {p}")
w("")
w("Note: git stores each distinct blob once, so identical files at different")
w("paths are counted under whichever path reaches them first. This is not")
w("cosmetic -- it reflects real storage. Two consequences worth knowing:")
w("")
w("  * test_data/chr6_ensemble.fa and data/chr6_transcripts.fa are byte-identical.")
w("    Both are stripped, so the shared blob genuinely goes away.")
w("")
w("  * test_data/isoncorrect/0.fastq, test_data/isoncorrect/1.fastq and")
w("    test_data/100reads.fq are ALL THE SAME FILE (one blob, three paths).")
w("    The 'two test clusters' used by CI and by bench/ are one cluster twice.")
w("    Stripping is path-based, so keeping them is still correct -- but do not")
w("    mistake them for independent test coverage.")

report = "\n".join(lines)
open(report_out, "w").write(report + "\n")
print(report)
PY

# ---------------------------------------------------------------------------
# Fixture verification, done against the trees rather than the object listing.
#
# A KEEP entry naming a path that does not exist protects nothing and would let
# a fixture be stripped silently, so this is a hard error.
# ---------------------------------------------------------------------------
{
  echo
  echo "Fixtures explicitly retained"
  echo "------------------------------------------------------------"
} | tee -a "$REPORT"

FIXTURE_ERROR=0
for p in "${KEEP[@]}"; do
  if git cat-file -e "HEAD:$p" 2>/dev/null; then
    blob="$(git rev-parse "HEAD:$p")"
    size="$(git cat-file -s "$blob")"
    # Other paths at HEAD sharing this exact blob. `|| true` because grep exits
    # non-zero when a fixture has no twins, which is the normal case.
    twins="$(git ls-tree -r HEAD | awk -v b="$blob" '$3==b {print $4}' | { grep -vFx "$p" || true; } | paste -sd', ' -)"
    line="$(printf '  %10.2f KB  %s' "$(echo "$size/1000" | bc -l)" "$p")"
    [[ -n "$twins" ]] && line="$line"$'\n'"             shares content with: $twins"
  elif [[ -n "$(git log --all --format=%H -1 -- "$p" 2>/dev/null)" ]]; then
    line="  $(printf '%10s' 'history')  $p   (not in HEAD, but present in history)"
  else
    line="  $(printf '%10s' 'MISSING')  $p   <-- ERROR: path not found in HEAD or history"
    FIXTURE_ERROR=1
  fi
  echo "$line" | tee -a "$REPORT"
done

if [[ $FIXTURE_ERROR -eq 1 ]]; then
  {
    echo
    echo "ERROR: the KEEP list names paths that do not exist. Fix the KEEP array in"
    echo "analyze.sh before running slim.sh -- those entries protect nothing."
  } | tee -a "$REPORT"
fi

echo
echo "==> wrote $REMOVAL"
echo "==> wrote $REPORT"
echo

if [[ $FIXTURE_ERROR -eq 1 ]]; then
  echo "REFUSING to proceed: fix the KEEP list first." >&2
  exit 1
fi

echo "Review removal-paths.txt, then run: tools/repo-slim/slim.sh"
