#!/usr/bin/env bash
#
# Create (or refresh) the pinned Python reference environment and record exactly
# what got resolved. The resolved-versions file is what makes a golden run
# auditable later — without it, "the goldens changed" is unanswerable.
#
# Usage:
#   bench/setup_reference_env.sh            # create if missing, then verify
#   bench/setup_reference_env.sh --force    # tear down and recreate
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_NAME="${ISONCORRECT_REF_ENV:-isoncorrect-ref}"
ENV_FILE="$REPO_ROOT/bench/env/reference.yml"

FORCE=0
[[ "${1:-}" == "--force" ]] && FORCE=1

if ! command -v conda >/dev/null 2>&1; then
  echo "error: conda not found on PATH." >&2
  echo "Install miniforge (https://github.com/conda-forge/miniforge) and re-run." >&2
  exit 1
fi

# mamba resolves this environment far faster than classic conda; use it if present.
SOLVER="conda"
command -v mamba >/dev/null 2>&1 && SOLVER="mamba"

env_exists() { conda env list | awk '{print $1}' | grep -qx "$ENV_NAME"; }

if [[ $FORCE -eq 1 ]] && env_exists; then
  echo "==> removing existing env '$ENV_NAME'"
  conda env remove -n "$ENV_NAME" -y
fi

if env_exists; then
  echo "==> env '$ENV_NAME' already exists (use --force to recreate)"
else
  echo "==> creating env '$ENV_NAME' with $SOLVER"
  "$SOLVER" env create -n "$ENV_NAME" -f "$ENV_FILE"
fi

# Use the environment's interpreter directly rather than `conda run`: conda run
# does not forward stdin, which silently swallows heredoc-fed scripts.
PREFIX="$(conda env list | awk -v n="$ENV_NAME" '$1==n {print $NF; exit}')"
if [[ -z "$PREFIX" || ! -x "$PREFIX/bin/python" ]]; then
  echo "error: could not locate python for env '$ENV_NAME'" >&2
  exit 1
fi
PY_BIN="$PREFIX/bin/python"
export PATH="$PREFIX/bin:$PATH"

echo "==> installing isONcorrect (editable) from $REPO_ROOT"
"$PY_BIN" -m pip install -e "$REPO_ROOT" --no-deps --quiet

echo "==> verifying"
"$PY_BIN" - <<'PY'
import importlib, shutil, subprocess, sys

missing = []
for mod in ("edlib", "parasail", "numpy", "isoncorrect.isONcorrect"):
    try:
        importlib.import_module(mod)
    except Exception as exc:  # noqa: BLE001 - want the reason, whatever it is
        missing.append(f"{mod}: {exc}")

spoa = shutil.which("spoa")
if spoa is None:
    missing.append("spoa: binary not found on PATH")

if missing:
    print("FAILED:", file=sys.stderr)
    for m in missing:
        print("  -", m, file=sys.stderr)
    sys.exit(1)

# isONcorrect shells out to a bare `time`, so it must exist as an executable and
# not merely as a shell builtin.
if shutil.which("time") is None:
    print("FAILED: no `time` executable on PATH (run_isoncorrect shells out to it)", file=sys.stderr)
    sys.exit(1)

print("ok")
PY

PLATFORM="$("$PY_BIN" -c 'import sysconfig; print(sysconfig.get_platform())')"
RESOLVED="$REPO_ROOT/bench/env/resolved-${PLATFORM}.txt"

echo "==> recording resolved versions to bench/env/resolved-${PLATFORM}.txt"
{
  echo "# Resolved reference environment. Generated by bench/setup_reference_env.sh."
  echo "# Goldens recorded under a different set of versions are not comparable."
  echo "platform: $PLATFORM"
  echo "env_name: $ENV_NAME"
  echo
  echo "## key versions"
  "$PY_BIN" - <<'PY'
import subprocess, sys
import edlib, numpy, parasail

print(f"python: {sys.version.split()[0]}")
print(f"numpy: {numpy.__version__}")
print(f"parasail: {parasail.__version__}")
print(f"edlib: {getattr(edlib, '__version__', 'unknown')}")
# spoa writes its version to stdout and exits 0.
try:
    v = subprocess.run(["spoa", "--version"], capture_output=True, text=True, timeout=30)
    print(f"spoa: {(v.stdout or v.stderr).strip()}")
except Exception as exc:  # noqa: BLE001
    print(f"spoa: UNKNOWN ({exc})")
PY
  echo
  echo "## full conda list"
  conda list -n "$ENV_NAME"
} > "$RESOLVED"

echo
sed -n '1,20p' "$RESOLVED"
echo
echo "Reference environment ready. Activate with:  conda activate $ENV_NAME"
